#!/usr/bin/env node

/**
 * Register Babel and JXS require support
 */
require('node-jsx').install({
	extension: '.jsx'
});
require('babel/register');

/**
 * Start the server
 */
require('../server/index.js');
